version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: cadastre_db_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SuperSecretPassword123!
      - POSTGRES_DB=cadastre_db
    ports:
      - "5432:5432"
    volumes:
      - cadastre_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadastre_web_container
    depends_on:
      - db
    ports:
      - "9000:8080"  # Изменили внешний порт с 8080 на 9000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=cadastre_db;Username=postgres;Password=SuperSecretPassword123!;
    volumes:
      - cadastre_uploads:/app/wwwroot/uploads
    restart: unless-stopped

volumes:
  cadastre_pgdata:
  cadastre_uploads: